fixtures:
  repositories:
    stdlib:        "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:        "https://github.com/voxpupuli/puppet-extlib"
    apache:        "https://github.com/puppetlabs/puppetlabs-apache.git"
    cron_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-cron_core'
      puppet_version: '>= 6.0.0'
    vcsrepo:       "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    postgresql:    "https://github.com/puppetlabs/puppetlabs-postgresql.git"
    mongodb:       "https://github.com/voxpupuli/puppet-mongodb.git"
    concat:        "https://github.com/puppetlabs/puppetlabs-concat.git"
    xinetd:        "https://github.com/puppetlabs/puppetlabs-xinetd.git"
    certs:
      repo: "https://github.com/theforeman/puppet-certs.git"
      ref: '10.0.0'
    katello:
      repo: "https://github.com/theforeman/puppet-katello.git"
      ref: '16.0.0'
    candlepin:
      repo: "https://github.com/theforeman/puppet-candlepin.git"
      ref: '11.0.0'
    pulp:
      repo: "https://github.com/theforeman/puppet-pulp.git"
      ref: '8.1.0'
    qpid:
      repo: "https://github.com/theforeman/puppet-qpid.git"
      ref: '6.1.0'
    foreman:
      repo: "https://github.com/theforeman/puppet-foreman.git"
      ref: '16.0.0'
    foreman_proxy:
      repo: "https://github.com/theforeman/puppet-foreman_proxy.git"
      ref: '16.0.0'
    redis:         "https://github.com/voxpupuli/puppet-redis"
    tftp:          "https://github.com/theforeman/puppet-tftp.git"
    squid:         "https://github.com/voxpupuli/puppet-squid.git"
    datacat:       "https://github.com/richardc/puppet-datacat"
    selinux:       "https://github.com/voxpupuli/puppet-selinux"
    selinux_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-selinux_core'
      puppet_version: '>= 6.0.0'
    systemd:       "https://github.com/camptocamp/puppet-systemd"
    transition:    "https://github.com/puppetlabs/puppetlabs-transition.git"
