fixtures:
  repositories:
    stdlib:        "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:        "git://github.com/puppet-community/puppet-extlib"
    apache:        "git://github.com/puppetlabs/puppetlabs-apache.git"
    vcsrepo:       "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    postgresql:    "git://github.com/puppetlabs/puppetlabs-postgresql.git"
    mongodb:       "git://github.com/puppetlabs/puppetlabs-mongodb.git"
    concat:        "git://github.com/puppetlabs/puppetlabs-concat.git"
    xinetd:        "git://github.com/puppetlabs/puppetlabs-xinetd.git"
    certs:         "git://github.com/theforeman/puppet-certs.git"
    katello:       "git://github.com/theforeman/puppet-katello.git"
    common:        "git://github.com/theforeman/puppet-common.git"
    candlepin:     "git://github.com/theforeman/puppet-candlepin.git"
    pulp:          "git://github.com/theforeman/puppet-pulp.git"
    qpid:          "git://github.com/theforeman/puppet-qpid.git"
    foreman:       "git://github.com/theforeman/puppet-foreman.git"
    foreman_proxy: "git://github.com/theforeman/puppet-foreman_proxy.git"
    tftp:          "git://github.com/theforeman/puppet-tftp.git"
    squid3:        "git://github.com/thias/puppet-squid3.git"
    datacat:       "git://github.com/richardc/puppet-datacat"
  symlinks:
    katello_devel: "#{source_dir}"
