name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.4"
          - "2.5"
        puppet:
          - "5.0"
          - "6.0"
        exclude:
          - ruby: "2.4"
            puppet: "6.0"
          - ruby: "2.5"
            puppet: "5.0"
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
        env:
          PUPPET_VERSION: "${{ matrix.puppet }}"
